# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'NY Times MPA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.1'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'SDWebImage', '~> 5.7'
  pod 'ReachabilitySwift', '~> 5.0'
  pod 'NVActivityIndicatorView', '~> 4.8'

end
